---
dist: trusty
sudo: false

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.5.0
  # - ANSIBLE_VERSION=2.4.4.0
  # - ANSIBLE_VERSION=2.4.3.0
  # - ANSIBLE_VERSION=2.4.2.0
  # - ANSIBLE_VERSION=2.4.1.0
  # - ANSIBLE_VERSION=2.4.0.0
  # - ANSIBLE_VERSION=2.3.3.0
  # - ANSIBLE_VERSION=2.3.2.0
  # - ANSIBLE_VERSION=2.3.1.0
  # - ANSIBLE_VERSION=2.3.0.0
  # - ANSIBLE_VERSION=2.2.3.0
  # - ANSIBLE_VERSION=2.2.2.0
  # - ANSIBLE_VERSION=2.2.1.0
  # - ANSIBLE_VERSION=2.2.0.0
  # - ANSIBLE_VERSION=2.1.6
  # - ANSIBLE_VERSION=2.1.5
  # - ANSIBLE_VERSION=2.1.4
  # - ANSIBLE_VERSION=2.1.3
  # - ANSIBLE_VERSION=2.1.2
  # - ANSIBLE_VERSION=2.1.1.0
  # - ANSIBLE_VERSION=2.1.0.0
  # - ANSIBLE_VERSION=2.0.2.0
  # - ANSIBLE_VERSION=2.0.1.0
  # - ANSIBLE_VERSION=2.0.0.2
  # - ANSIBLE_VERSION=2.0.0.1
  # - ANSIBLE_VERSION=2.0.0.0

branches:
  only:
    - master

before_install:
  - apt-get update -qq
  - apt-get -y install aptitude

  # Remove lxc-docker and docker.io
  - apt-get remove --purge --yes lxc-docker* docker.io* || true

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # Test installation
  - >
    sudo docker run hello-world
    | grep -q 'Hello from Docker'
    && (echo 'Installation test: pass' && exit 0)
    || (echo 'Installation test: fail' && exit 1)
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml || true; fi

notifications:
  email: false
  hipchat:
    rooms:
      secure: GPUtM44MpgqN/3+TXw4Onp7TpF6YOKpVQkB/sfwGYS1oHUCkp2eb3eGGfJAIUtNxkfFVkdUxM/Bp9GMCnpVjJwRRZP6hYUmlpjCHl8CiK2MjbLvzV65qqBAqYl5bLzKkmmRdPiC31m9ixMe4TiAhJFBK1NoETOP1LkCJ04ezL6U=
webhooks: https://galaxy.ansible.com/api/v1/notifications/
