---
### Download, configure and install mailcow-dockerized.

# TODO: (optional)
#  Modify docker-compose to add a bind mount for Nextcloud with s3ql

- name: Clone mailcow repo.
  git:
    repo: https://github.com/mailcow/mailcow-dockerized
    version: master
    dest: "{{ mc_install_dir }}"
    clone: yes
    update: yes
    force: yes

- name: Create a generate_config_non_interactive file with settings from template.
  template:
    src: generate_config_non_interactive.j2
    dest: "{{ mc_install_dir }}/generate_config_non_interactive.sh"
    mode: a+x

- name: Append only the non-interactive portion of generate_config.sh.
  shell: cat generate_config.sh | sed -n -e '/cat << EOF > mailcow.conf/,$p' >> generate_config_non_interactive.sh
  args:
    executable: /bin/bash
    chdir: "{{ mc_install_dir }}"

# intermittently the script uses the busybox version of grep and fails, thus force bash
- name: Generate mailcow configuration using non-interactive script (only runs once).
  shell: ./generate_config_non_interactive.sh
  args:
    executable: /bin/bash
    chdir: "{{ mc_install_dir }}"
    creates: "{{ mc_install_dir }}/mailcow.conf"

- name: Insert nextcloud subdomain into mailcow.conf for SSL certificate generation.
  lineinfile:
    path: "{{ mc_install_dir }}/mailcow.conf"
    regexp: "^ADDITIONAL_SAN"
    line: "ADDITIONAL_SAN={{ mc_nextcloud_subdomain }}.{{ mc_domain }}"
    state: present

- name: Insert watchdog notify email into mailcow.conf.
  lineinfile:
    path: "{{ mc_install_dir }}/mailcow.conf"
    regexp: "^#WATCHDOG_NOTIFY_EMAIL="
    line: "WATCHDOG_NOTIFY_EMAIL={{ mc_email }}"
    state: present

# TODO: Fix ansible error on Debian Buster
- name: Pull docker images & start containers (this takes a while).
  docker_compose:
    project_src: "{{ mc_install_dir }}"
    pull: yes
    state: present # equivalent to docker-compose up
  when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"

- name: Pull docker images (this takes a while).
  shell: docker-compose pull
  args:
    executable: /bin/bash
    chdir: "{{ mc_install_dir }}"
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Start containers.
  shell: docker-compose up -d
  args:
    executable: /bin/bash
    chdir: "{{ mc_install_dir }}"
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"
# Fix - end.

- name: Create file to flag that mailcow has been installed already.
  file:
    path: "{{ mc_install_dir }}/mailcow.installed"
    state: touch
